#!/usr/bin/env bash
# Per-boot startup for the baby-lovable Cloud Agent environment.
#
# Brings up the Docker daemon and the local Supabase stack, then writes
# `.env.local` (gitignored) pointing the host app + CLI at the local stack.
# Injected Cloud Agent secrets (AI_GATEWAY_API_KEY, DAYTONA_API_KEY,
# FREESTYLE_API_KEY) stay in the process environment and take precedence, so we
# never write them to disk.
#
# Must tolerate restarts: it detects an already-running daemon/stack.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

log() { echo "[start] $*"; }

# Docker 29 nftables backend is broken here; keep legacy iptables selected.
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy || true
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || true

# ---------------------------------------------------------------------------
# 1. Docker daemon
# ---------------------------------------------------------------------------
if ! docker info >/dev/null 2>&1; then
  log "Starting dockerd ..."
  sudo rm -f /var/run/docker.pid >/dev/null 2>&1 || true
  sudo dockerd --storage-driver=fuse-overlayfs >/tmp/dockerd.log 2>&1 &

  for _ in $(seq 1 60); do
    if sudo docker info >/dev/null 2>&1; then break; fi
    sleep 1
  done
fi
sudo chmod 666 /var/run/docker.sock || true

if ! docker info >/dev/null 2>&1; then
  log "ERROR: docker daemon did not become ready; see /tmp/dockerd.log" >&2
  exit 1
fi
log "docker ready: $(docker --version)"

# ---------------------------------------------------------------------------
# 2. Local Supabase stack (idempotent — reuses containers if already up).
# ---------------------------------------------------------------------------
log "Starting local Supabase stack ..."
supabase start >/tmp/supabase-start.log 2>&1 || {
  log "supabase start failed; recent log:" >&2
  tail -20 /tmp/supabase-start.log >&2 || true
  exit 1
}

# ---------------------------------------------------------------------------
# 3. Generate .env.local for the host app + CLI.
# ---------------------------------------------------------------------------
STATUS_ENV="$(supabase status -o env 2>/dev/null || true)"

get() { printf '%s\n' "$STATUS_ENV" | grep -m1 "^$1=" | cut -d= -f2- | tr -d '"'; }

API_URL="$(get API_URL)"
PUBLISHABLE_KEY="$(get PUBLISHABLE_KEY)"
SECRET_KEY="$(get SECRET_KEY)"

: "${API_URL:=http://127.0.0.1:54321}"
AI_MODEL_VALUE="${AI_MODEL:-zai/glm-5.3-flash}"

cat > "$REPO_ROOT/.env.local" <<EOF
# Auto-generated by .cursor/start.sh — points at the local Supabase stack.
# Injected Cloud Agent secrets (AI_GATEWAY_API_KEY, DAYTONA_API_KEY,
# FREESTYLE_API_KEY) come from the process environment and are NOT written here.
AI_MODEL=${AI_MODEL_VALUE}
BABY_LOVABLE_DEV_USER_ID=11111111-1111-1111-1111-111111111111

NEXT_PUBLIC_SUPABASE_URL=${API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
SUPABASE_SECRET_KEY=${SECRET_KEY}

DAYTONA_API_URL=https://app.daytona.io/api
DAYTONA_TARGET=us
DAYTONA_DEV_PORT=3000
DAYTONA_SNAPSHOT=baby-lovable-nextjs-starter-2g-warm2
EOF

log ".env.local written (Supabase URL: ${API_URL})"
log "start complete. Run 'npm run dev' or 'npm run agent -- -l'."
